# Project
mod_version=1.8.37
group=org.cyclops.integratedtunnels
java_version=21

# Common
minecraft_version=1.21.1
mod_name=IntegratedTunnels
mod_author=rubensworks (aka kroeser)
mod_id=integratedtunnels
license=MIT
github_url=https://github.com/CyclopsMC/IntegratedTunnels
issue_tracker_url=https://github.com/CyclopsMC/IntegratedTunnels/issues
display_url=https://www.curseforge.com/minecraft/mc-mods/integrated-tunnels
description=Transfer other stuff over Integrated Dynamics networks.
fingerprint=bd0353b3e8a2810d60dd584e256e364bc3bedd44

parchment_version=2024.07.07
parchment_minecraft_version=1.21
curseforge_project_id=251389
modrinth_project_id=Etqy1Omb

# NeoForge
neoforge_version=21.1.2
neoforge_loader_version_range=[4,)
neoforge_update_json_url=https://raw.githubusercontent.com/CyclopsMC/Versions/master/neoforge_update/integrated-tunnels.json

# Dependencies
cyclopscore_version=1.25.5-643
integrateddynamics_version=1.24.1-1004
integratedtunnelscompat_version=1.0.0-45
commoncapabilities_version=2.9.3-147
