modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/CyclopsMC/IntegratedTunnels/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/integrated-tunnels"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="integratedtunnels"
version="${file.jarVersion}"
displayName="IntegratedTunnels"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/integrated-tunnels.json"
description='''
Transfer other stuff over Integrated Dynamics networks.
'''
[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"
[[dependencies.integratedtunnels]]
    modId="cyclopscore"
    type="required"
    versionRange="[1.19.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedtunnels]]
    modId="integrateddynamics"
    type="required"
    versionRange="[1.21.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedtunnels]]
    modId="commoncapabilities"
    type="required"
    versionRange="[2.9.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedtunnels]]
    modId="neoforge"
    type="required"
    versionRange="[20.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedtunnels]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4,]"
    ordering="NONE"
    side="BOTH"
