modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/CyclopsMC/IntegratedTunnels/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/integrated-tunnels"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="integratedtunnels"
version="${file.jarVersion}"
displayName="IntegratedTunnels"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/integrated-tunnels.json"
description='''
Transfer other stuff over Integrated Dynamics networks.
'''
[[dependencies.integratedtunnels]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.11.6,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedtunnels]]
    modId="integrateddynamics"
    mandatory=true
    versionRange="[1.8.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedtunnels]]
    modId="commoncapabilities"
    mandatory=true
    versionRange="[2.7.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedtunnels]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedtunnels]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,]"
    ordering="NONE"
    side="BOTH"
